{% set name = "mcp" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcp-{{ version }}.tar.gz
  sha256: d9324876de2c5637369f43161cd71eebfd803df5a95e46225cab8d280e366723

build:
  skip: true  # [py<310]
  # entry_points:
  #   - mcp = mcp.cli:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - anyio >=4.5
    - httpx >=0.27
    - httpx-sse >=0.4
    - pydantic >=2.7.2,<3.0.0
    - pydantic-settings >=2.5.2
    # - python-dotenv >=1.0.0
    - rich >=13.9.4
    - sse-starlette >=1.6.1
    - starlette >=0.27
    # - typer >=0.12.4
    - uvicorn >=0.23.1

test:
  imports:
    - mcp
  commands:
    - pip check
    # - mcp --help
  requires:
    - pip
    - python

about:
  summary: Model Context Protocol SDK
  home: https://github.com/modelcontextprotocol/python-sdk
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
